### ISSUE TITLE
typo in README

### ISSUE THREAD

**Issue by jurajhrib** [jvddavid/cloudflare-images#1]
Hey, first of all, great package! I was looking for a nodejs client for Images service and this one seems to be perfect for what I need.

I bumped into a typo in README. 

Here in the Auth section:
https://github.com/jvddavid/cloudflare-images/blob/main/README.md#auth

The import of library is misspelled "jvvdavid" instead of "jvddavid". I copied that line into my terminal to "yarn add...", and it thrown an error. For a while, I thought the package is not available at NPM anymore. But then I noticed that it's just a typo :-)

Have a great rest of the week!

**Comment by jvddavid** [comment]
Thanks for letting me know, I corrected it here.
